name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "feature/**", "epic/**", "release/**", "test/release/*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
          arguments: compileDebugSources --no-configuration-cache -Pnapt=true

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-configuration-cache -Pnapt=true